protected/modules/blog/models/Post.php
<?php

/**
 * This is the model class for table "{{blog_posts}}".
 *
 * The followings are the available columns in table '{{blog_posts}}':
 * @property string $id
 * @property string $theme
 * @property string $content
 * @property string $status
 * @property string $created
 * @property string $user_id
 * @property integer $comment_status
 * @property string $views_count
 * @property string $good_votes
 * @property string $bad_votes
 * @property integer $is_top
 *
 */
class Post extends CActiveRecord
{
        const STATUS_PUBLISHED = 1; // Опубликовано
        const STATUS_DRAFT     = 2; // Черновик
        const STATUS_ARCHIVED  = 3; // Архив

        public $highlighter = false;

        	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Post the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{blog_posts}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('theme, content', 'required'),
			array('comment_status, is_top', 'numerical', 'integerOnly'=>true),
			array('theme', 'length', 'max'=>255),
			array('post_status', 'length', 'max'=>1),
			array('created', 'length', 'max'=>11),
			array('user_id, views_count, good_votes, bad_votes', 'length', 'max'=>20),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, theme, content, post_status, created, user_id, comment_status, views_count, good_votes, bad_votes, is_top', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
                Yii::import('application.models.*');
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
                        'tags' => array(self::MANY_MANY,'Tags',"{{blog_posts_tags}}(tag_id,post_id)"),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'theme' => 'Заголовок',
			'content' => 'Текст записи',
			'post_status' => 'Статус записи',
			'created' => 'Создана',
			'user_id' => 'Автор',
			'comment_status' => 'Комментарии разрешены',
			'views_count' => 'Количество просмотров',
			'good_votes' => 'Понравилось',
			'bad_votes' => 'Не понравилось',
			'is_top' => 'Всегда сверху',
                        'tags' => 'Теги'
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('theme',$this->theme,true);
		$criteria->compare('content',$this->content,true);
		$criteria->compare('post_status',$this->post_status,true);
		$criteria->compare('created',$this->created,true);
		$criteria->compare('user_id',$this->user_id,true);
		$criteria->compare('comment_status',$this->comment_status);
		$criteria->compare('views_count',$this->views_count,true);
		$criteria->compare('good_votes',$this->good_votes,true);
		$criteria->compare('bad_votes',$this->bad_votes,true);
		$criteria->compare('is_top',$this->is_top);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

        public function behaviors(){
             return array('CSaveRelationsBehavior' => array('class' => 'application.components.CSaveRelationsBehavior'));
        }

        protected function beforeSave()
        {
            if(parent::beforeSave())
            {
                if($this->isNewRecord)
                {
                    $this->created=time();
                    $this->user_id=Yii::app()->user->id;
                }
                $this->updated=time();
                //$this->content = str_replace ('<cut />', '<cut /><a name="cut"></a>', $this->content);
                return true;
            }
            else
                return false;
        }

        public function scopes()
        {
            return array(
                'published'=>array(
                    'condition'=>'post_status='.Post::STATUS_PUBLISHED,
                ),
                'recently'=>array(
                    'order'=>'t.is_top DESC, t.created DESC',
                ),
            );
        }

        public function defaultScope()
        {
            $condition = array(
                'condition' => 'post_status='.Post::STATUS_PUBLISHED,
                'order'=>'is_top DESC, created DESC'
            );
            if( ! Yii::app()->user->isGuest) {
                $condition['condition'] .= ' OR (post_status='.Post::STATUS_DRAFT.' AND user_id='.Yii::app()->user->id.')';
            }
            if(Yii::app()->request->getParam('id')) {
                $condition['condition'] .= ' OR (post_status='.Post::STATUS_ARCHIVED.')';
            }
            return $condition;
        }

        public function __toString()
        {
            return $this->getContent();
        }

        public function all()
        {
           return $this;
        }

        public function getHighlighter() {
            if( ! $this->highlighter) {
                $this->highlighter = new CTextHighlighter;
            }
            return $this->highlighter;
        }

        public function highlightCode($matches) {
            if(isset($matches[2])) {
                $h = $this->getHighlighter();
                if(isset($matches[1]) && $matches[1] !== '<code>' && $matches[1] !== '``') {
                    $h->language = $matches[1];
                }else{
                    $h->language = 'javascript';
                }
                if($matches[1] !== '``') {
                    return '<div class="code par">' . $h->highlight($matches[2]) . '</div>';
                }else{
                    return '<span class="inline">' . $h->highlight($matches[2]) . '</span>';
                }
            }
            return '';
        }

        public function delBr($matches) {
            if(isset($matches[1])) {
                return '<pre>'.str_replace('<br />', '', $matches[1]).'</pre>';
            }
        }

        public function getContent() {
            $content = preg_replace('#<jsf src="(.*)" tabs="(.*)" styles="(.*)"><\/jsf>#', '<iframe class="jsfiddle-embedded"  style="$3"  src="$1embedded/$2" allowfullscreen="allowfullscreen" frameborder="0"></iframe>', $this->content);

            $content = preg_replace_callback('#<code lang="(.*)">(.*)<\/code>#imsU', array($this, 'highlightCode'), $content);// function($matches) {
            $content = preg_replace_callback('#(<code>)(.*)<\/code>#imsU', array($this, 'highlightCode'), $content);// function($matches) {
            $content = preg_replace_callback('#(``)(.*)``#imsU', array($this, 'highlightCode'), $content);// function($matches) {


            return preg_replace_callback('#<pre>(.*)<\/pre>#imsU', array($this, 'delBr'), nl2br($content));
        }

        public function getUrl()
        {
            return Yii::app()->createUrl('blog/post/view',
                array(
                    'id' => $this->id,
                    'theme' => Text::translitURL($this->theme),
                )
            );
        }

        public function getDisqusIdentifier()
        {
            return 'post_'.$this->id;
        }


        public function getPostDate() {
            return date('d.m.Y г., в h:i', $this->created);
        }

        public function getPostRating() {
            return $this->good_votes - $this->bad_votes;
        }

        public function listStatus() {
            return array(
                Post::STATUS_PUBLISHED => 'Опубликовано',
                Post::STATUS_DRAFT => 'Черновик',
                Post::STATUS_ARCHIVED => 'Архив',
            );
        }

        public function listTags() {
            return CHtml::listData(Tags::model()->findAll(), 'id', 'tag');
        }

        public function getCutted() {
            $pos = strpos($this->getContent(), '<cut />');
            if($pos === FALSE) {
                return $this->getContent();
            }
            $cutted = substr($this->getContent(), 0, strpos($this->getContent(), '<cut />'));
            $cutted .= Yii::app()->controller->renderPartial('blog.views.post._cut', array('data'=>$this), true);
            return $cutted;
        }


}

protected/modules/blog/controllers/PostController.php
<?php

class PostController extends Controller
{

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';
    private $_model;

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array_merge(parent::filters(), array(
            'accessControl', // perform access control for CRUD operations
                /* array(
                  'COutputCache + index',
                  'duration' => 86400,
                  'dependency' => array(
                  'class' => 'CChainedCacheDependency',
                  'dependencies' => array(
                  new CDbCacheDependency('SELECT MAX(updated) FROM {{blog_posts}}'),
                  new CExpressionDependency('Yii::app()->user->isGuest'),
                  ),
                  ),
                  'varyByParam' => array('Post_page'),
                  ),
                  array(
                  'COutputCache + view',
                  'duration' => 86400,
                  'dependency' => array(
                  'class' => 'CChainedCacheDependency',
                  'dependencies' => array(
                  new CDbCacheDependency('SELECT MAX(updated) FROM {{blog_posts}}'),
                  new CExpressionDependency('Yii::app()->user->isGuest'),
                  ),
                  ),
                  'varyByParam' => array('id'),
                  ), */
        ));
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'viewTest'),
                'users' => array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update'),
                'users' => array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     */
    public function actionView($id)
    {
        $post = $this->loadModel($id);
        if( ! isset($_GET['theme']) || Text::translitURL($post->theme) !== $_GET['theme']) {
            Yii::app()->request->redirect($post->getUrl(), true, 301);
        }
        if (!Yii::app()->session->get('view_post_' . $post->id))
        {
            $post->saveCounters(array('views_count' => 1));
            Yii::app()->session['view_post_' . $post->id] = TRUE;
        }
        $this->pageTitle = Yii::app()->name . ' - ' . $post->theme;
        $this->render('view', array(
            'model' => $post,
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Post;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Post']))
        {
            $model->attributes = $_POST['Post'];
            $model->setRelationRecords('tags', $_POST['Post']['tags']);
            if ($model->save())
                $this->redirect(array('view', 'id' => $model->id));
        }

        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['Post']))
        {
            $model->attributes = $_POST['Post'];
            $model->setRelationRecords('tags', $_POST['Post']['tags']);
            //$model->tags->add() = $_POST['Post']['tags'];
            if ($model->save())
            {
                //foreach ($_POST['Post']['tags'] as $tag) {
                //}
                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        if (Yii::app()->request->isPostRequest)
        {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        }
        else
            throw new CHttpException(400, 'Invalid request. Please do not repeat this request again.');
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider(Post::model()->all(), array(
                    'criteria' => array(
                        'with' => array('user', 'tags'),
                    ),
                    'pagination' => array(
                        'pageSize' => $this->module->postPerPage,
                    ),
                ));
        $this->pageTitle = Yii::app()->name . ' - Лента';
        $this->render('index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model = new Post('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Post']))
            $model->attributes = $_GET['Post'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id)
    {
        if ($this->_model === null)
        {
            if (isset($_GET['id']))
            {
                if (Yii::app()->user->isGuest)
                    $condition = 'post_status=' . Post::STATUS_PUBLISHED
                            . ' OR post_status=' . Post::STATUS_ARCHIVED;
                else
                    $condition = '';
                $this->_model = Post::model()->findByPk($id, $condition);
            }
            if ($this->_model === null)
                throw new CHttpException(404, 'Запрашиваемая страница не найдена.');
        }
        return $this->_model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'post-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/modules/blog/views/post/_cut.php
    <div class="post-cut">
        <?= CHtml::link('Читать дальше', $data->url.'#cut', array('class' => 'icon-cut')) ?>
    </div>

protected/modules/blog/views/post/_footer.php
<div class="post-footer">
    <div class="block gray icon-clock cursor-help" title="Время публикации"><?= $data->postDate ?></div>
    <!-- <div class="block gray icon-heart"><?= $data->postRating ?></div> -->
    <div class="block gray icon-eye cursor-help" title="Количество просмотров"><?= $data->views_count ?></div>
    <?php if (!$data->comment_status && !$view): ?>
        <div class="block right icon-comments-disabled">Комментирование отключено</div>
    <?php elseif (!$view): ?>
        <div class="block right icon-comments cursor-help" title="Количество комментариев">
            <?= CHtml::link('Комментировать', 'http://wer.su' . $data->url . '#disqus_thread') ?>
        </div>
    <?php endif; ?>
</div>

protected/modules/blog/views/post/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'post-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'theme'); ?>
		<?php echo $form->textField($model,'theme',array('size'=>114,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'theme'); ?>
	</div>

	<div class="row">
            <?php echo $form->labelEx($model,'content'); ?>
            <?php $this->widget('ext.markitup.EMarkitupWidget', array(
                'model' => $model,
                'attribute' => 'content',
                'options' => array(
                    'resizeHandle' => false,
                    'previewInWindow' => 'width=800, height=600, resizable=yes, scrollbars=yes',
                    'markupSet' => array(
                        array(
                            'name' => 'Жирный',
                             'openWith' => '<b>',
                             'closeWith' => '</b>',
                        ),
                        array(
                            'name' => 'Наклонный',
                             'openWith' => '<em>',
                             'closeWith' => '</em>',
                        ),
                        array(
                            'name' => 'Зачеркнутый',
                             'openWith' => '<del>',
                             'closeWith' => '</del>',
                        ),
                        array(
                            'separator' => '----------------'
                        ),
                        array(
                            'name' => 'Цитата',
                            'openWith' => '<blockquote>',
                            'closeWith' => '</blockquote>',
                        ),
                        array(
                            'name' => 'Сарказм',
                             'openWith' => '<p class="sarcasm">',
                             'closeWith' => '</p>',
                        ),
                        array(
                            'separator' => '----------------'
                        ),
                        array(
                            'name' => 'Ссылка',
                             'openWith' => '<a href="[![Ссылка:!:http://]!]">',
                             'closeWith' => '[![Текст]!]</a>',
                        ),
                        array(
                            'separator' => '----------------'
                        ),
                        array(
                            'name' => 'Код',
                            //'openWith' => '<jsf src="[![JSFiddle:!:]!]" tabs="js,html,css,result" styles="width: 100%; height:300px;">',
                            // 'closeWith' => '</jsf>',
                            'dropMenu' => array(
                                array(
                                    'name' => 'Javascript',
                                    'openWith' => '<code lang="javascript">',
                                    'closeWith' => '</code>',
                                ),
                                array(
                                    'name' => 'PHP',
                                    'openWith' => '<code lang="php">',
                                    'closeWith' => '</code>',
                                ),
                                array(
                                    'name' => 'SQL',
                                    'openWith' => '<code lang="sql">',
                                    'closeWith' => '</code>',
                                ),
                                array(
                                    'name' => 'HTML',
                                    'openWith' => '<code lang="html">',
                                    'closeWith' => '</code>',
                                ),
                                 array(
                                    'name' => 'JSFiddle',
                                    'openWith' => '<jsf src="[![JSFiddle]!]" tabs="js,html,css,result" styles="width: 100%; height:300px;">',
                                    'closeWith' => '</jsf>',
                                ),
                            )
                        ),
                    ),
                )

            )); ?>
		<?php echo $form->error($model,'content'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'post_status'); ?>
		<?php echo $form->dropdownlist($model,'post_status',$model->listStatus()); ?>
		<?php echo $form->error($model,'post_status'); ?>
	</div>

        <div class="row">
            <?php echo $form->labelEx($model,'tags'); ?>
            <?php echo $form->dropDownList($model, 'tags',$model->listTags(), array('multiple'=>'multiple', 'size'=>5, 'style' => 'width: 100%' )); ?>
            <?php echo $form->error($model,'tags'); ?>
        </div>



	<div class="row">
		<?php echo $form->labelEx($model,'comment_status'); ?>
		<?php echo $form->checkBox($model,'comment_status'); ?>
		<?php echo $form->error($model,'comment_status'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'is_top'); ?>
		<?php echo $form->checkBox($model,'is_top'); ?>
		<?php echo $form->error($model,'is_top'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Опубликовать' : 'Сохранить'); ?>
	</div>


<?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/blog/views/post/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'theme'); ?>
		<?php echo $form->textField($model,'theme',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'content'); ?>
		<?php echo $form->textArea($model,'content',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'post_status'); ?>
		<?php echo $form->textField($model,'post_status',array('size'=>1,'maxlength'=>1)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'created'); ?>
		<?php echo $form->textField($model,'created',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user_id'); ?>
		<?php echo $form->textField($model,'user_id',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'comment_status'); ?>
		<?php echo $form->textField($model,'comment_status'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'views_count'); ?>
		<?php echo $form->textField($model,'views_count',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'good_votes'); ?>
		<?php echo $form->textField($model,'good_votes',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'bad_votes'); ?>
		<?php echo $form->textField($model,'bad_votes',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'is_top'); ?>
		<?php echo $form->textField($model,'is_top'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/blog/views/post/_view.php
<div class="view">

	<h1>
            <?php if($data->is_top): ?>
                <span class="icon-pin-big cursor-help" title="Всегда сверху"></span>
            <?php endif; ?>

            <?php if($data->post_status == Post::STATUS_DRAFT): ?>
                <span class="icon-lock-big cursor-help" title="Черновик"></span>
            <?php endif; ?>

            <?php echo CHtml::link(CHtml::encode($data->theme), $data->url); ?>
        </h1>

        <?= Yii::app()->controller->renderPartial('blog.views.tags._index', array('data'=>$data->tags), true) ?>

        <div class="post-content">
            <?php echo $data->cutted; ?>
	</div>

        <?= Yii::app()->controller->renderPartial('blog.views.post._footer', array('data'=>$data, 'view'=>false), true) ?>

</div>

protected/modules/blog/views/post/admin.php
<?php
$this->breadcrumbs=array(
	'Posts'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Post', 'url'=>array('index')),
	array('label'=>'Create Post', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('post-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Posts</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'post-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'theme',
		'post_status',
		'postDate',
		/*
		'comment_status',
		'views_count',
		'good_votes',
		'bad_votes',
		'is_top',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/modules/blog/views/post/create.php
<?php
$this->breadcrumbs=array(
	//'Posts'=>array('index'),
	'Новый пост',
);
?>

<h1>Новая запись</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/blog/views/post/update.php
<?php
$this->breadcrumbs=array(
	//'Posts'=>array('index'),
	$model->theme => ('/post/'.$model->id.'/'.$model->theme),
	'Редактирование',
);

?>

<h1>Редактирование записи</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/blog/views/post/view.php
<?php
$this->breadcrumbs = array(
    //'Posts'=>array('index'),
    $model->theme,
);
?>

<h1>
    <?php if ($model->is_top): ?>
        <span class="icon-pin-big cursor-help" title="Всегда сверху"></span>
    <?php endif; ?>

    <?php if ($model->post_status == Post::STATUS_DRAFT): ?>
        <span class="icon-lock-big cursor-help" title="Черновик"></span>
    <?php endif; ?>

    <?php if ($model->post_status == Post::STATUS_ARCHIVED): ?>
        <span class="icon-denied cursor-help" title="В архиве"></span>
    <?php endif; ?>

    <?php echo $model->theme; ?>
</h1>

<?= Yii::app()->controller->renderPartial('blog.views.tags._index', array('data' => $model->tags), true) ?>

<div class="post-content">
    <?= $model ?>
</div>

<?= Yii::app()->controller->renderPartial('blog.views.post._footer', array('data' => $model, 'view' => true), true) ?>

<a name="comments"></a>
<?php
//Yii::import('blog.widgets.CommentsWidget');
if ($model->comment_status)
{
    $this->widget('DisqusWidget', array(
        'disqus_identifier' => $model->id,
        'disqus_title' => $model->theme,
        'disqus_url' => Yii::app()->params->disqus['host'] . $model->url,
    ));
}
?>

<?php if (!$model->comment_status): ?>
    <h2 class="comments-h2">комментирование отключено</h2>
<?php endif; ?>