protected/modules/blog/models/Tags.php
<?php

/**
 * This is the model class for table "{{blog_tags}}".
 *
 * The followings are the available columns in table '{{blog_tags}}':
 * @property string $id
 * @property string $tag
 *
 * The followings are the available model relations:
 * @property PostsTags[] $postsTags
 */
class Tags extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Tags the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{blog_tags}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('tag, alias', 'required'),
			array('tag, alias', 'length', 'max'=>255),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, tag', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'posts' => array(self::MANY_MANY,'Post',"{{blog_posts_tags}}(post_id,tag_id)"),
                        'lastUpdateTime' => array(self::STAT,'Post',"{{blog_posts_tags}}(post_id,tag_id)", 'select' => 'MAX(updated)'),
                        //'postsCount' => array(self::STAT,'Post',"{{blog_posts_tags}}(post_id,tag_id)"),
                        //'viewsCount' => array(self::STAT,'Post',"{{blog_posts_tags}}(post_id,tag_id)", 'select' => 'distinct sum(views_count)'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'tag' => 'Tag',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('tag',$this->tag,true);
                $criteria->compare('alias',$this->alias,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

        /*public function getCommentablePost() {
            if($this->postsCount) {
                $criteria=new CDbCriteria;
                $criteria->select = '*, id as ppost_id';
                $criteria->condition = 'id in ( select post_id from {{blog_posts_tags}} where tag_id ='.$this->id.')';
                $criteria->order='(select count(*) from {{comments}} where owner_id = ppost_id) desc';
                $criteria->limit = 1;
                return Post::model()->find($criteria);
            }
            return NULL;
        }*/

        public function getPopularPost() {
            if($this->postsCount) {
                $criteria=new CDbCriteria;
                $criteria->condition = 'id in ( select post_id from {{blog_posts_tags}} where tag_id ='.$this->id.')';
                $criteria->order='views_count desc';
                $criteria->limit = 1;
                return Post::model()->find($criteria);
            }
            return NULL;
        }

        public function getUrl()
        {
            return Yii::app()->createUrl('blog/tags/view',
                array(
                    'tag' => $this->alias,
                )
            );
        }

        public function getPostsCount() {
            return count($this->posts);
        }

        public function getViewsCount() {
            $count = 0;
            foreach($this->posts as $post) {
                $count += $post->views_count;
            };
            return $count;
        }

}

protected/modules/blog/controllers/TagsController.php
<?php

class TagsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($tag)
	{
                $tag = $this->getByAlias($tag);
		$dataProvider=new CArrayDataProvider($tag->posts, array(
                    'pagination'=>array(
                        'pageSize' => $this->module->postPerPage,
                        'route'     => '/',
                    ),
                ));
		$this->render('view',array(
			'dataProvider'=>$dataProvider,
                        'model' => $tag,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Tags;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Tags']))
		{
			$model->attributes=$_POST['Tags'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Tags']))
		{
			$model->attributes=$_POST['Tags'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Tags', array(
                    'criteria'=>array(
                        'order' => 'tag asc',
                    ),
                    'pagination'=>array(
                        'pageSize' => 10,
                    ),
                ));
                //$dataProvider->criteria->addCondition('postsCount > 0');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Tags('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Tags']))
			$model->attributes=$_GET['Tags'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Tags::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	public function getByAlias($tag)
	{
		$model=Tags::model()->findByAttributes(array('alias'=>  urldecode($tag)));
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='tags-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/blog/views/tags/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'tags-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'tag'); ?>
		<?php echo $form->textField($model,'tag',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'tag'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/blog/views/tags/_index.php
<?php foreach($data as $tag): ?>
    <a href="/tag/<?=  urlencode($tag->alias)?>" class="float-left tag"><?=$tag->tag?></a>
<?php endforeach; ?>
<div class="tags-clear"></div>

protected/modules/blog/views/tags/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tag'); ?>
		<?php echo $form->textField($model,'tag',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/blog/views/tags/_view.php
<?php if($data->postsCount): ?>
    <div class="tag-widget">
        <h1 class="float-left sub-main"><a class="icon-tag-big" href="<?=$data->url?>"><?=$data->tag?></a></h1>
        <div class="info">
            <div>всего статей: <?= $data->postsCount ?></div>
            <div>просмотров: <?= $data->viewsCount ?></div>
        </div>
        <div class="clear"></div>

        <div>Самая популярная статья: <a href="<?= $data->popularPost->url ?>"><?= $data->popularPost->theme ?></a></div>

    </div>
<?php endif; ?>

protected/modules/blog/views/tags/admin.php
<?php
$this->breadcrumbs=array(
	'Tags'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Tags', 'url'=>array('index')),
	array('label'=>'Create Tags', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('tags-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Tags</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'tags-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'tag',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/modules/blog/views/tags/create.php
<?php
$this->breadcrumbs=array(
	'Tags'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Tags', 'url'=>array('index')),
	array('label'=>'Manage Tags', 'url'=>array('admin')),
);
?>

<h1>Create Tags</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/blog/views/tags/update.php
<?php
$this->breadcrumbs=array(
	'Tags'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Tags', 'url'=>array('index')),
	array('label'=>'Create Tags', 'url'=>array('create')),
	array('label'=>'View Tags', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Tags', 'url'=>array('admin')),
);
?>

<h1>Update Tags <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/blog/views/tags/view.php
<?php
//var_dump($dataProvider);
$this->breadcrumbs=array(
	'Теги'=>'/tags',
	$model->tag,
);
?>

<?= Yii::app()->controller->renderPartial('_view', array('data'=>$model), true) ?>

<!---<div class="icon-rss right"><a href="#">RSS</a></div>-->

<?php
    $this->widget('BlogListView', array(
            'dataProvider'=> $dataProvider,
            'itemView'=>'blog.views.post._view',
            'template'=>"{items}\n{pager}",
            'ajaxUpdate' =>false,
            'pager'=>array(
                'cssFile'=>false,
                'header'=>false,
                'prevPageLabel'=>'←',
                'nextPageLabel'=>'→',
            ),
    ));

    $this->widget('DisqusCount');
?>